WebApplication1/Areas/Home/Controllers/AboutProjectController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Areas.Home.Controllers
{
    [Area("Home")]
    public class AboutProjectController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Areas/Home/Views/Shared/AddMusicForm.cshtml
<link rel="stylesheet" href="~/css/AddForm.css" />
<div class="form-container" id="addMusicForm">
    <h4>Добавить новую музыку</h4>
    <form asp-action="AddMusic" method="post">
        <input type="hidden" name="playlistId" value="@Model.Id" />
        <div class="form-group">
            <label for="YouTubeLink">Ссылка на YouTube</label>
            <input type="text" name="YouTubeLink" class="form-control" required pattern="^(https?:\/\/)?(www\.)?(youtube\.com\/watch\?v=|youtu\.be\/|music\.youtube\.com\/watch\?v=).+$" title="The YouTube link is not valid." />
        </div>
        <button type="submit" class="btn btn-primary">Добавить</button>
        <button type="button" class="btn btn-secondary" onclick="hideAddMusicForm()">Назад</button>
    </form>
</div>

WebApplication1/Areas/Home/Views/Shared/AddPlaylistForm.cshtml
<link rel="stylesheet" href="~/css/AddForm.css" />
<div class="form-container" id="addPlaylistForm">
    <h4>Добавить новый плейлист</h4>
    <form asp-action="AddPlaylist" method="post">
        <input type="hidden" name="serverId" value="@Model.Id" />
        <div class="form-group">
            <label for="playlistName">Название плейлиста</label>
            <input type="text" name="playlistName" class="form-control" required />
        </div>
        <button type="submit" class="btn btn-primary">Добавить плейлист</button>
        <button type="button" class="btn btn-secondary" onclick="hideAddPlaylistForm()">Назад</button>
    </form>
</div>

WebApplication1/Areas/Home/Views/Shared/LeftMenu.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Recommendation</title>
    <link href="~/css/LeftMenu.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 sidebar bg-dark">
                <h4 class="text-white">Lorderon</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Account" asp-action="Index">Мой аккаунт</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="AboutProject" asp-action="Index">Справка</a>
                    </li>
                </ul>
                <button id="backButton" class="btn btn-secondary mt-2 mr-2">Назад</button>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/LeftMenu.js"></script>
</body>
</html>

WebApplication1/Areas/Home/Views/Shared/LeftMenuNoBack.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Recommendation</title>
    <link href="~/css/LeftMenu.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 sidebar bg-dark">
                <h4 class="text-white">Lorderon</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Account" asp-action="Index">Мой аккаунт</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="AboutProject" asp-action="Index">Справка</a>
                    </li>
                </ul>
                <form action="/Authorization/Auth/Logout" method="post" class="logout-button">
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger">Logout</button>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/LeftMenu.js"></script>
</body>
</html>

WebApplication1/Areas/Home/Views/Shared/LeftMenuPlayLists.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Recommendation</title>
    <link href="~/css/LeftMenu.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 sidebar bg-dark">
                <h4 class="text-white">Lorderon</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Account" asp-action="Index">Мой аккаунт</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="AboutProject" asp-action="Index">Справка</a>
                    </li>
                </ul>
                <a class="nav-link text-white" asp-controller="ServerDetails" asp-action="ServerDetails" asp-route-serverId="@Model.ServerId">Назад</a>
                @* <button id="backButton" class="btn btn-secondary mt-2 mr-2">Назад</button> *@
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/LeftMenu.js"></script>
</body>
</html>

WebApplication1/Areas/Home/Views/Shared/LeftMenuServers.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Recommendation</title>
    <link href="~/css/LeftMenu.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 sidebar bg-dark">
                <h4 class="text-white">Lorderon</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Account" asp-action="Index">Мой аккаунт</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="AboutProject" asp-action="Index">Справка</a>
                    </li>
                </ul>
                <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Назад</a>
                @* <button type="button" class="btn btn-secondary" asp-area="Home" asp-controller="Home" asp-action="Index">Назад</button> *@
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

WebApplication1/Areas/Home/Views/Shared/LeftMenuWithBack.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Recommendation</title>
    <link href="~/css/LeftMenu.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 sidebar bg-dark">
                <h4 class="text-white">Lorderon</h4>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Account" asp-action="Index">Мой аккаунт</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="AboutProject" asp-action="Index">Справка</a>
                    </li>
                </ul>
                <button id="backButton" class="btn btn-secondary mt-2 mr-2">Назад</button>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="~/js/LeftMenu.js"></script>
</body>
</html>

WebApplication1/Areas/Home/Views/Shared/TrackItem.cshtml
@model DatabaseService.Models.Music

<div class="track-item">
    <div class="track-video embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/@GetYouTubeVideoId(Model.YouTubeLink)" allowfullscreen></iframe>
    </div>
    <div class="track-info">
        <h5>@Model.Title</h5>
        <p class="text-muted">@Model.Artist</p>
    </div>
    <div class="track-actions">
        <form asp-action="DeleteTrack" method="post" class="mt-2">
            <input type="hidden" name="trackId" value="@Model.Id" />
            <input type="hidden" name="playlistId" value="@Model.PlaylistId" />
            <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
        </form>
    </div>
</div>
@functions {
    private string GetYouTubeVideoId(string url)
    {
        var uri = new Uri(url);
        var query = System.Web.HttpUtility.ParseQueryString(uri.Query);
        return query["v"];
    }
}

WebApplication1/Areas/Home/Views/Shared/_EditPlaylistForm.cshtml
@model DatabaseService.Models.Playlist

<link rel="stylesheet" href="~/css/AddForm.css" />
<div class="form-container">
    <h4>Редактировать плейлист</h4>
    <form asp-action="EditPlaylist" method="post">
        <input type="hidden" name="playlistId" value="@Model.Id" />
        <input type="hidden" name="serverId" value="@ViewBag.ServerId" />
        <div class="form-group">
            <label for="playlistName">Название плейлиста</label>
            <input type="text" name="playlistName" class="form-control" value="@Model.Name" required />
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
        <button type="button" class="btn btn-secondary" onclick="hideEditPlaylistForm()">Отмена</button>
    </form>
</div>